export const generateMockCommunities = () => {
  const communities = [
    {
      id: 1,
      name: 'React Developers',
      description: 'A community for React developers to share knowledge, discuss best practices, and collaborate on projects.',
      category: 'tech',
      theme: 'modern',
      image: 'https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      members: 15420,
      posts: 2847,
      rating: 4.8,
      isJoined: true,
      isPremium: false
    },
    {
      id: 2,
      name: 'UI/UX Designers Hub',
      description: 'Connect with fellow designers, share your work, get feedback, and stay updated with the latest design trends.',
      category: 'design',
      theme: 'vibrant',
      image: 'https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      members: 8930,
      posts: 1654,
      rating: 4.9,
      isJoined: false,
      isPremium: true
    },
    {
      id: 3,
      name: 'Startup Founders',
      description: 'A place for entrepreneurs and startup founders to network, share experiences, and find potential co-founders.',
      category: 'business',
      theme: 'elegant',
      image: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      members: 12750,
      posts: 3421,
      rating: 4.7,
      isJoined: true,
      isPremium: true
    },
    {
      id: 4,
      name: 'Digital Nomads',
      description: 'For remote workers and digital nomads sharing travel tips, workspace recommendations, and lifestyle advice.',
      category: 'lifestyle',
      theme: 'nature',
      image: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      members: 22100,
      posts: 5632,
      rating: 4.6,
      isJoined: false,
      isPremium: false
    },
    {
      id: 5,
      name: 'Machine Learning',
      description: 'Discuss ML algorithms, share research papers, and collaborate on AI projects with fellow data scientists.',
      category: 'tech',
      theme: 'modern',
      image: 'https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      members: 18650,
      posts: 4123,
      rating: 4.9,
      isJoined: true,
      isPremium: true
    },
    {
      id: 6,
      name: 'Photography Masters',
      description: 'Share your photography work, learn new techniques, and get constructive feedback from professional photographers.',
      category: 'design',
      theme: 'warm',
      image: 'https://images.pexels.com/photos/1181715/pexels-photo-1181715.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      members: 31200,
      posts: 8947,
      rating: 4.8,
      isJoined: false,
      isPremium: false
    },
    {
      id: 7,
      name: 'Online Learning',
      description: 'Discover new courses, share learning resources, and connect with fellow lifelong learners.',
      category: 'education',
      theme: 'elegant',
      image: 'https://images.pexels.com/photos/1181719/pexels-photo-1181719.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      members: 14580,
      posts: 2156,
      rating: 4.7,
      isJoined: true,
      isPremium: false
    },
    {
      id: 8,
      name: 'Fitness Enthusiasts',
      description: 'Share workout routines, nutrition tips, and motivate each other on your fitness journey.',
      category: 'lifestyle',
      theme: 'vibrant',
      image: 'https://images.pexels.com/photos/1181724/pexels-photo-1181724.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      members: 27890,
      posts: 6234,
      rating: 4.5,
      isJoined: false,
      isPremium: false
    },
    {
      id: 9,
      name: 'Blockchain Developers',
      description: 'Explore blockchain technology, discuss smart contracts, and collaborate on Web3 projects.',
      category: 'tech',
      theme: 'modern',
      image: 'https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      members: 9420,
      posts: 1876,
      rating: 4.6,
      isJoined: false,
      isPremium: true
    },
    {
      id: 10,
      name: 'Creative Writers',
      description: 'A space for writers to share their work, get feedback, and participate in writing challenges.',
      category: 'education',
      theme: 'warm',
      image: 'https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      members: 11340,
      posts: 3567,
      rating: 4.8,
      isJoined: true,
      isPremium: false
    },
    {
      id: 11,
      name: 'Marketing Professionals',
      description: 'Share marketing strategies, discuss industry trends, and network with marketing professionals.',
      category: 'business',
      theme: 'nature',
      image: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      members: 16780,
      posts: 4321,
      rating: 4.7,
      isJoined: false,
      isPremium: false
    },
    {
      id: 12,
      name: 'Sustainable Living',
      description: 'Learn about eco-friendly practices, share sustainability tips, and make a positive environmental impact.',
      category: 'lifestyle',
      theme: 'nature',
      image: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      members: 19650,
      posts: 3892,
      rating: 4.9,
      isJoined: true,
      isPremium: false
    }
  ]

  return communities
}
